data:
  data_dir: "data/cafa-5-protein-function-prediction"
  embeddings_dir: "data/embeddings"
  embeddings_source: "ESM2"        # ESM2 | ProtBERT | T5
  num_labels: 500
  train_val_split: 0.9

model:
  type: "cnn1d"                      # mlp | cnn1d
  # MLP-specific
  mlp_hidden_dims: [864, 712]
  # CNN-specific
  cnn_out_channels: [3, 8]
  cnn_kernel_size: 3

training:
  epochs: 5
  batch_size: 128
  learning_rate: 0.001
  scheduler_factor: 0.1
  scheduler_patience: 1
  seed: 42

output:
  output_dir: "outputs"
